=== IMAGE-ET/mediboard_save/modules/dPlabo/remote/catalogue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Tom Desp (openXtrem) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="catalogue" type="typeCatalogue">
		<xs:annotation>
			<xs:documentation>Catalogue racine</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="typeCatalogue">
		<xs:annotation>
			<xs:documentation>Structure r√©cursive de catalogues et analyses</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="identifiant" type="xs:Name"/>
			<xs:element name="libelle" type="xs:string"/>
			<xs:element name="sections">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="catalogue" type="typeCatalogue"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="analyses">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="analyse" type="typeAnalyse"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="typeAnalyse">
		<xs:annotation>
			<xs:documentation>Contenu d'une analyse</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="identifiant" type="xs:Name"/>
			<xs:element name="libelle" type="xs:string"/>
			<xs:element name="type">
				<xs:complexType>
					<xs:choice>
						<xs:element name="numerique">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="unite" type="xs:string"/>
									<xs:element name="min" type="xs:decimal"/>
									<xs:element name="max" type="xs:decimal"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="ouiNon"/>
						<xs:element name="texteLibre"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="application" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="debut" type="xs:date" minOccurs="0"/>
						<xs:element name="fin" type="xs:date" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="applicabilite" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="sexe" type="typeSexe"/>
						<xs:element name="ageMinimum" type="xs:positiveInteger" minOccurs="0"/>
						<xs:element name="ageMaximum" type="xs:positiveInteger" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="prelevement" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="type" type="typePrelevement"/>
						<xs:element name="methode" type="xs:string"/>
						<xs:element name="quantite" type="xs:decimal"/>
						<xs:element name="unite" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="conservation" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="duree" type="xs:duration"/>
						<xs:element name="methode" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="execution" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="duree" type="xs:duration"/>
						<xs:element name="joursSemaine">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="lundi" type="xs:boolean"/>
									<xs:element name="mardi" type="xs:boolean"/>
									<xs:element name="mercredi" type="xs:boolean"/>
									<xs:element name="jeudi" type="xs:boolean"/>
									<xs:element name="vendredi" type="xs:boolean"/>
									<xs:element name="samedi" type="xs:boolean"/>
									<xs:element name="dimanche" type="xs:boolean"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="technique" type="xs:string" minOccurs="0"/>
			<xs:element name="materiel" type="xs:string" minOccurs="0"/>
			<xs:element name="remarques" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID"/>
	</xs:complexType>
	<xs:simpleType name="typeSexe">
		<xs:annotation>
			<xs:documentation>Homme, Femme ou Unisexe</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="homme"/>
			<xs:enumeration value="femme"/>
			<xs:enumeration value="unisexe"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typePrelevement">
		<xs:annotation>
			<xs:documentation>Biopsie, Sang ou Urine</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="bopsie"/>
			<xs:enumeration value="sang"/>
			<xs:enumeration value="urine"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== IMAGE-ET/mediboard_save/modules/dPlabo/remote/catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample catalogue file -->
<catalogue id="ctl-1" xsi:noNamespaceSchemaLocation="catalogue.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<identifiant>Name1</identifiant>
	<libelle>String 1</libelle>
	<sections>
	  <catalogue id="ctl-11">
				<identifiant>NAME11</identifiant>
				<libelle>String 11</libelle>
				<sections />
				<analyses />
		</catalogue>
	  <catalogue id="ctl-12">
				<identifiant>NAME12</identifiant>
				<libelle>String 12</libelle>
				<sections />
				<analyses />
		</catalogue>
	</sections>
	<analyses>
		<analyse id="anl-A">
			<identifiant>NAMEA</identifiant>
			<libelle>String</libelle>
			<type>
				<numerique>
					<unite>String A</unite>
					<min>0.0</min>
					<max>0.0</max>
				</numerique>
			</type>
			<application>
				<debut>1967-08-13</debut>
				<fin>1967-08-13</fin>
			</application>
			<applicabilite>
				<sexe>homme</sexe>
				<ageMinimum>7</ageMinimum>
				<ageMaximum>77</ageMaximum>
			</applicabilite>
			<prelevement>
				<type>sang</type>
				<methode>String</methode>
				<quantite>0.0</quantite>
				<unite>String</unite>
			</prelevement>
			<conservation>
				<duree>P1Y2M3DT10H30M0S</duree>
				<methode>String</methode>
			</conservation>
			<execution>
				<duree>P1Y2M3DT10H30M0S</duree>
				<joursSemaine>
					<lundi>true</lundi>
					<mardi>false</mardi>
					<mercredi>true</mercredi>
					<jeudi>false</jeudi>
					<vendredi>true</vendredi>
					<samedi>false</samedi>
					<dimanche>true</dimanche>
				</joursSemaine>
			</execution>
			<technique>String</technique>
			<materiel>String</materiel>
			<remarques>String</remarques>
		</analyse>
		<analyse id="anl-B">
			<identifiant>NameB</identifiant>
			<libelle>String B</libelle>
			<type>
				<texteLibre />
			</type>
			<applicabilite>
				<sexe>unisexe</sexe>
				<ageMaximum>80</ageMaximum>
			</applicabilite>
		</analyse>
		<analyse id="anl-C">
			<identifiant>NameC</identifiant>
			<libelle>String C</libelle>
			<type>
				<ouiNon />
			</type>
			<applicabilite>
				<sexe>femme</sexe>
				<ageMinimum>2</ageMinimum>
			</applicabilite>
		</analyse>
	</analyses>
</catalogue>
